"""
Phase 8 -- PDF Report Generator

Generates a comprehensive threat analysis PDF report using fpdf2.
All dynamic text is sanitized to ASCII for Helvetica font compatibility.
"""

import os
import sys
import uuid
from datetime import datetime
from typing import Dict, Any, List

from fpdf import FPDF

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config


def sanitize_text(text):
    """Replace Unicode characters with ASCII equivalents for PDF compatibility."""
    if not isinstance(text, str):
        return str(text) if text else ""
    replacements = {
        '\u2014': '--', '\u2013': '-', '\u2018': "'", '\u2019': "'",
        '\u201c': '"', '\u201d': '"', '\u2022': '*', '\u2026': '...',
        '\u00a0': ' ', '\u200b': '', '\u2192': '->', '\u2190': '<-',
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    text = text.encode('latin-1', errors='replace').decode('latin-1')
    return text


SEVERITY_COLORS = {
    "critical": (220, 38, 38),
    "high": (234, 88, 12),
    "medium": (202, 138, 4),
    "low": (22, 163, 74),
}
HEADER_BG = (30, 41, 59)
HEADER_TEXT = (255, 255, 255)
ROW_ALT = (241, 245, 249)
ACCENT = (59, 130, 246)


class ThreatReport(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(100, 100, 100)
            self.cell(0, 8, "Email Threat Analysis Report", align="L")
            self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(200, 200, 200)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by Email Threat Analyzer -- For authorized use only", align="C")


def generate_report(analysis_data):
    pdf = ThreatReport()
    pdf.set_title("Email Threat Analysis Report")
    pdf.set_author("Email Threat Analyzer")

    case_id = f"ETA-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    risk_result = analysis_data.get("risk_result", {})
    severity = risk_result.get("severity", "low")
    score = risk_result.get("score", 0)

    # Cover Page
    pdf.add_page()
    _build_cover_page(pdf, case_id, timestamp, severity, score, analysis_data)

    # Content Pages
    pdf.add_page()

    llm_analysis = analysis_data.get("llm_analysis", {})
    _add_executive_summary(pdf, llm_analysis, risk_result)
    _add_email_metadata(pdf, analysis_data.get("parsed_email", {}))
    _add_header_analysis(pdf, analysis_data.get("header_analysis", {}))
    _add_ioc_table(pdf, analysis_data.get("iocs", {}), analysis_data.get("enrichment", {}))
    _add_ml_classification(pdf, analysis_data.get("ml_result", {}))

    if analysis_data.get("attachment_results"):
        _add_attachment_analysis(pdf, analysis_data["attachment_results"])

    _add_mitre_mapping(pdf, risk_result, llm_analysis)

    if llm_analysis.get("threat_narrative"):
        _add_threat_narrative(pdf, llm_analysis)

    _add_recommended_actions(pdf, llm_analysis)
    _add_score_breakdown(pdf, risk_result)

    filename = f"report_{case_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(config.REPORTS_DIR, filename)
    pdf.output(filepath)
    return filepath


def _build_cover_page(pdf, case_id, timestamp, severity, score, analysis_data):
    pdf.set_fill_color(*HEADER_BG)
    pdf.rect(0, 0, 210, 297, "F")

    pdf.set_y(60)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*HEADER_TEXT)
    pdf.cell(0, 15, "EMAIL THREAT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 15, "ANALYSIS REPORT", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    sev_color = SEVERITY_COLORS.get(severity, (100, 100, 100))
    pdf.set_fill_color(*sev_color)
    badge_x = (210 - 80) / 2
    pdf.set_x(badge_x)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(80, 16, f"{severity.upper()}", align="C", fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(180, 180, 180)
    pdf.cell(0, 10, f"Risk Score: {score}/100", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(15)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(200, 200, 200)
    details = [
        f"Case ID: {case_id}",
        f"Generated: {timestamp}",
        sanitize_text(f"Subject: {analysis_data.get('parsed_email', {}).get('subject', 'N/A')[:60]}"),
        sanitize_text(f"From: {analysis_data.get('parsed_email', {}).get('from_address', 'N/A')}"),
        f"Findings: {analysis_data.get('risk_result', {}).get('finding_count', 0)}",
    ]
    for detail in details:
        pdf.cell(0, 8, detail, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(260)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "CONFIDENTIAL -- For authorized security personnel only", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "Generated by Email Threat Analyzer with AI-powered analysis", align="C", new_x="LMARGIN", new_y="NEXT")


def _section_header(pdf, title):
    pdf.ln(6)
    pdf.set_fill_color(*ACCENT)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*HEADER_TEXT)
    pdf.cell(0, 9, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_text_color(0, 0, 0)


def _add_executive_summary(pdf, llm_analysis, risk_result):
    _section_header(pdf, "EXECUTIVE SUMMARY")
    summary = llm_analysis.get("executive_summary", "")
    if not summary:
        severity = risk_result.get("severity", "low")
        score = risk_result.get("score", 0)
        summary = f"This email has been assessed with a risk score of {score}/100 ({severity} severity). "
        summary += f"{risk_result.get('finding_count', 0)} security findings were identified during analysis."
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, sanitize_text(summary))
    pdf.ln(3)


def _add_email_metadata(pdf, parsed_email):
    _section_header(pdf, "EMAIL METADATA")
    fields = [
        ("From", parsed_email.get("from", "N/A")),
        ("To", parsed_email.get("to", "N/A")),
        ("Subject", parsed_email.get("subject", "N/A")),
        ("Date", parsed_email.get("date", "N/A")),
        ("Reply-To", parsed_email.get("reply_to", "N/A") or "Same as From"),
        ("Message-ID", parsed_email.get("message_id", "N/A")),
        ("Attachments", str(parsed_email.get("attachment_count", 0))),
        ("Hops", str(parsed_email.get("hop_count", 0))),
    ]
    pdf.set_font("Helvetica", "", 9)
    for i, (label, value) in enumerate(fields):
        if i % 2 == 0:
            pdf.set_fill_color(*ROW_ALT)
        else:
            pdf.set_fill_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(35, 6, sanitize_text(label), border=1, fill=True)
        pdf.set_font("Helvetica", "", 9)
        display_val = str(value)[:80] if value else "N/A"
        pdf.cell(0, 6, sanitize_text(display_val), border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)


def _add_header_analysis(pdf, header_analysis):
    _section_header(pdf, "HEADER ANALYSIS")
    anomalies = header_analysis.get("anomalies", [])
    if not anomalies:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 6, "No header anomalies detected.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
        return

    auth = header_analysis.get("authentication", {})
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Authentication Results:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    for protocol in ["spf", "dkim", "dmarc"]:
        status = auth.get(protocol, {}).get("status", "unknown")
        icon = "PASS" if status == "pass" else ("FAIL" if status in ("fail", "softfail") else "N/A")
        pdf.cell(0, 5, f"  {protocol.upper()}: {icon} ({status})", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, f"Anomalies Found ({len(anomalies)}):", new_x="LMARGIN", new_y="NEXT")

    for anomaly in anomalies:
        sev = anomaly.get("severity", "info")
        sev_color = SEVERITY_COLORS.get(sev, (100, 100, 100))
        pdf.set_fill_color(*sev_color)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(18, 5, sev.upper(), fill=True)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 9)
        msg = anomaly.get("message", "")[:90]
        pdf.cell(0, 5, sanitize_text(f"  {msg}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)


def _add_ioc_table(pdf, iocs, enrichment):
    _section_header(pdf, "INDICATORS OF COMPROMISE (IOCs)")
    all_iocs = []
    for url in iocs.get("urls", [])[:8]:
        verdict = _get_enrichment_verdict(enrichment, url)
        all_iocs.append(("URL", url[:55], verdict))
    for ip in iocs.get("public_ips", [])[:5]:
        verdict = _get_enrichment_verdict(enrichment, ip)
        all_iocs.append(("IP", ip, verdict))
    for domain in iocs.get("domains", [])[:5]:
        verdict = _get_enrichment_verdict(enrichment, domain)
        all_iocs.append(("Domain", domain[:40], verdict))
    for h in iocs.get("hashes", [])[:3]:
        verdict = _get_enrichment_verdict(enrichment, h.get("sha256", ""))
        all_iocs.append(("Hash", h.get("sha256", "")[:40] + "...", verdict))

    if not all_iocs:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 6, "No IOCs extracted from this email.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
        return

    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, f"Total IOCs: {iocs.get('total_count', 0)}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_fill_color(*HEADER_BG)
    pdf.set_text_color(*HEADER_TEXT)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(20, 6, "Type", border=1, fill=True)
    pdf.cell(115, 6, "Value", border=1, fill=True)
    pdf.cell(0, 6, "Verdict", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 8)

    for i, (ioc_type, value, verdict) in enumerate(all_iocs):
        if i % 2 == 0:
            pdf.set_fill_color(*ROW_ALT)
        else:
            pdf.set_fill_color(255, 255, 255)
        pdf.cell(20, 5, sanitize_text(ioc_type), border=1, fill=True)
        pdf.cell(115, 5, sanitize_text(value), border=1, fill=True)
        if verdict == "malicious":
            pdf.set_text_color(*SEVERITY_COLORS["critical"])
        elif verdict == "suspicious":
            pdf.set_text_color(*SEVERITY_COLORS["medium"])
        else:
            pdf.set_text_color(*SEVERITY_COLORS["low"])
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, sanitize_text(verdict.upper()), border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 8)
    pdf.ln(3)


def _add_ml_classification(pdf, ml_result):
    _section_header(pdf, "ML PHISHING CLASSIFICATION")
    if not ml_result:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 6, "ML classification was not performed.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
        return

    label = ml_result.get("label", "unknown")
    confidence = ml_result.get("confidence", 0)
    phishing_prob = ml_result.get("phishing_probability", 0)
    model = ml_result.get("model_used", "unknown")

    pdf.set_font("Helvetica", "B", 12)
    if label == "phishing":
        pdf.set_text_color(*SEVERITY_COLORS["critical"])
        pdf.cell(0, 8, "Verdict: PHISHING", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_text_color(*SEVERITY_COLORS["low"])
        pdf.cell(0, 8, "Verdict: LEGITIMATE", new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Confidence: {confidence:.1%}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Phishing Probability: {phishing_prob:.1%}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Model: {model}", new_x="LMARGIN", new_y="NEXT")

    # Confidence bar
    pdf.ln(3)
    bar_width = 150
    bar_height = 8
    bar_x = pdf.get_x() + 10
    bar_y = pdf.get_y()

    pdf.set_fill_color(220, 220, 220)
    pdf.rect(bar_x, bar_y, bar_width, bar_height, "F")

    fill_width = bar_width * phishing_prob
    if phishing_prob > 0.7:
        pdf.set_fill_color(*SEVERITY_COLORS["critical"])
    elif phishing_prob > 0.4:
        pdf.set_fill_color(*SEVERITY_COLORS["medium"])
    else:
        pdf.set_fill_color(*SEVERITY_COLORS["low"])
    pdf.rect(bar_x, bar_y, fill_width, bar_height, "F")

    pdf.set_font("Helvetica", "", 7)
    pdf.set_xy(bar_x, bar_y + bar_height + 1)
    pdf.cell(bar_width / 2, 4, "Legitimate", align="L")
    pdf.cell(bar_width / 2, 4, "Phishing", align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)


def _add_attachment_analysis(pdf, attachment_results):
    _section_header(pdf, "ATTACHMENT ANALYSIS")
    for att in attachment_results:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, sanitize_text(f"File: {att.get('filename', 'unknown')}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"  Size: {att.get('size_bytes', 0):,} bytes", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 5, f"  Type: {att.get('true_file_type', 'unknown')}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 5, f"  Risk: {att.get('risk_level', 'low').upper()}", new_x="LMARGIN", new_y="NEXT")
        hashes = att.get("hashes", {})
        if hashes:
            pdf.cell(0, 5, f"  SHA256: {hashes.get('sha256', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
        for finding in att.get("findings", []):
            sev = finding.get("severity", "info")
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*SEVERITY_COLORS.get(sev, (100, 100, 100)))
            pdf.cell(0, 5, sanitize_text(f"    [{sev.upper()}] {finding.get('message', '')}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
        pdf.ln(3)


def _add_mitre_mapping(pdf, risk_result, llm_analysis):
    _section_header(pdf, "MITRE ATT&CK MAPPING")
    techniques = risk_result.get("mitre_techniques", [])
    llm_techniques = llm_analysis.get("mitre_analysis", [])

    if not techniques and not llm_techniques:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 6, "No MITRE ATT&CK techniques mapped.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
        return

    for tech in techniques:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*ACCENT)
        pdf.cell(0, 6, sanitize_text(f"{tech.get('id', '')} - {tech.get('name', '')}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, sanitize_text(f"  Tactic: {tech.get('tactic', 'N/A')}"), new_x="LMARGIN", new_y="NEXT")
        pdf.multi_cell(0, 5, sanitize_text(f"  {tech.get('description', '')}"))
        pdf.ln(2)

    seen_ids = {t.get("id", "") for t in techniques}
    for tech in llm_techniques:
        if tech.get("technique_id", "") not in seen_ids:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*ACCENT)
            pdf.cell(0, 6, sanitize_text(f"{tech.get('technique_id', '')} - {tech.get('technique_name', '')}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", "I", 9)
            pdf.multi_cell(0, 5, sanitize_text(f"  AI Analysis: {tech.get('reasoning', '')}"))
            pdf.ln(2)
    pdf.ln(3)


def _add_threat_narrative(pdf, llm_analysis):
    _section_header(pdf, "AI THREAT NARRATIVE")
    narrative = llm_analysis.get("threat_narrative", "")
    if narrative:
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, sanitize_text(narrative))
        pdf.ln(2)
    confidence = llm_analysis.get("confidence_assessment", "")
    if confidence:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, sanitize_text(f"Analyst Confidence: {confidence}"))
        pdf.set_text_color(0, 0, 0)
    model = llm_analysis.get("llm_model", "")
    if model:
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 5, f"Generated by: {model}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
    pdf.ln(3)


def _add_recommended_actions(pdf, llm_analysis):
    _section_header(pdf, "RECOMMENDED ACTIONS")
    actions = llm_analysis.get("recommended_actions", [])
    if not actions:
        actions = ["No specific actions recommended -- continue normal monitoring."]
    pdf.set_font("Helvetica", "", 10)
    for i, action in enumerate(actions, 1):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(8, 6, f"{i}.")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, sanitize_text(action))
        pdf.ln(1)
    pdf.ln(3)


def _add_score_breakdown(pdf, risk_result):
    _section_header(pdf, "RISK SCORE BREAKDOWN")
    findings = risk_result.get("findings", [])
    score = risk_result.get("score", 0)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, f"Total Score: {score}/100 ({risk_result.get('severity', 'N/A').upper()})", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    if not findings:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 6, "No findings contributed to the risk score.", new_x="LMARGIN", new_y="NEXT")
        return

    pdf.set_fill_color(*HEADER_BG)
    pdf.set_text_color(*HEADER_TEXT)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(15, 6, "Pts", border=1, fill=True, align="C")
    pdf.cell(15, 6, "Sev", border=1, fill=True, align="C")
    pdf.cell(30, 6, "Category", border=1, fill=True)
    pdf.cell(0, 6, "Description", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 8)

    for i, finding in enumerate(findings):
        if i % 2 == 0:
            pdf.set_fill_color(*ROW_ALT)
        else:
            pdf.set_fill_color(255, 255, 255)
        pdf.cell(15, 5, f"+{finding.get('points', 0)}", border=1, fill=True, align="C")
        sev = finding.get("severity", "info")
        pdf.cell(15, 5, sev[:4].upper(), border=1, fill=True, align="C")
        pdf.cell(30, 5, sanitize_text(finding.get("category", "")[:15]), border=1, fill=True)
        desc = finding.get("description", "")[:70]
        pdf.cell(0, 5, sanitize_text(desc), border=1, fill=True, new_x="LMARGIN", new_y="NEXT")


def _get_enrichment_verdict(enrichment, ioc_value):
    if not enrichment or ioc_value not in enrichment:
        return "unknown"
    entry = enrichment[ioc_value]
    for source_data in entry.get("sources", {}).values():
        if isinstance(source_data, dict):
            verdict = source_data.get("verdict", "")
            if verdict == "malicious":
                return "malicious"
            if verdict == "suspicious":
                return "suspicious"
    return "clean"
